version: '3.2'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - "5000:5000"
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - ./.env.db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

